/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SnippetId = IDL.Nat;
export const Snippet = IDL.Record({
  'id' : SnippetId,
  'title' : IDL.Text,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Text,
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSnippet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteSnippet' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getSnippets' : IDL.Func([], [IDL.Vec(Snippet)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SnippetId = IDL.Nat;
  const Snippet = IDL.Record({
    'id' : SnippetId,
    'title' : IDL.Text,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Text,
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'addSnippet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteSnippet' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSnippets' : IDL.Func([], [IDL.Vec(Snippet)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };